# Generated by Django 5.2.1 on 2025-06-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('initial_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('discription', models.CharField()),
                ('brand', models.CharField()),
                ('product_image', models.ImageField(upload_to='product_image')),
            ],
        ),
    ]
