# Generated by Django 5.2.3 on 2025-06-23 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_products_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
    ]
