# Generated by Django 5.2.3 on 2025-06-23 06:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('women', 'women'), ('men', 'men')], default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
