# Generated by Django 5.2.3 on 2025-06-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_products_colors_products_material_products_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Merrel', 'Merrel'), ('Gucci', 'Gucci'), ('Skechers', 'Skechers')], max_length=10),
        ),
    ]
