# Generated by Django 5.2.3 on 2025-06-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_products_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Colors',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Blue', 'Blue'), ('Red', 'Red'), ('Green', 'Green'), ('Grey', 'Grey'), ('Orange', 'Orange'), ('Cream', 'Cream'), ('Brown', 'Brown')], max_length=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='Material',
            field=models.CharField(choices=[('Leather', 'Leather'), ('Suede', 'Suedue')], max_length=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='Size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='Style',
            field=models.CharField(choices=[('Oxfords', 'Oxfords'), ('Lace_Ups', 'Lace_Ups'), ('Sandals', 'Sandals'), ('Boots', 'Boots'), ('Slip_Ons', 'Slip_Ons')], max_length=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='Technologies',
            field=models.CharField(choices=[('BioBevel', 'BioBevel'), ('Groove', 'Groove'), ('FlexBevel', 'FlexBevel')], max_length=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='Width',
            field=models.CharField(choices=[('M', 'M'), ('W', 'W')], max_length=1),
        ),
    ]
